Tools/aliTreePlayer.py
Tools/test_aliTreePlayer.py
tutorial/distortionCase/test_Distortion.py

* aliTreePlayer: problems due to commit before with pop list
* testDistortion: renamed function to disable test due to missing data
* test_aliTreePlayer: test_Tree disabled due to missing data

Python2->Python3 transition, mistake in commit before, missing data excluded

---

RootInteractive/Tools/histoNDTools.py
RootInteractive/Tools/makePDFMaps.py

Hello Marian, Marian, Martin and Alperen,
in this draft pull request I would like to show you the modifications I did to get this functionality to work for the space-charge calibration studies.
1) In the makeHistogram function, I tried to compactify the data frame usage to avoid as many copies as possible. This gets relevant when working with big data frames. If you have further ideas on how to optimize the code for memory usage or compress the objects, please let me know.
2) I applied a quick fix in the makePdfMaps function. It avoids errors when the bins to fit are empty, setting means, rms and meansOK flag to 0. Something similar is done for medians and quantiles when the last bin in the loop is reached. However, here probably some values different from 0 could be set but I did not …

Changes in makeHistogram and makePdfMaps functions

---

RootInteractive/Tools/Histograms/__init__.py
requirements.txt
setup.py
virtualenv.md

Module request is not available anymore:
```
Singularity> python3 -m pip install request
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement request (from versions: none)
ERROR: No matching distribution found for request
```
The git repo is also down: https://github.com/looking-for-a-job/request.py
Therefore, the RootInteractive installation fails.
Here I change the module to requests, which I hope does the same. 
Test which are done for the singularity containers pass:
```
pytest /lustre/alice/users/miranov/github/RootInteractive/RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py 
pytest /lustre/alice/users/miranov/github/RootInteractive/RootInteractive/InteractiveDrawing/bokeh/test_bokehDra …
```

Python module request -> requests

---

RootInteractive/Tools/Histograms/benchmark_histogramdd_pytorch.py

This PR adds benchmarking code to the PyTorch N-dimensional histogramming tool. This is the file of the benchmark output on my machine. Times are in ms per one histogram.
Numpy: 
|    |     1e2 |     1e3 |     1e4 |     1e5 |     1e6 |     1e7 |
|----|---------|---------|---------|---------|---------|---------|
|  3 |  0.2095 |  0.3139 |  1.3679 | 11.4454 | 157.021 | 1960.69 |
|  4 |  0.3308 |  0.4531 |  1.8226 | 16.9595 | 219.219 | 2662.92 |
|  5 |  3.1293 |  3.2811 |  4.9445 | 24.8206 | 286.331 | 3574.78 |
|  6 | 34.408  | 34.6864 | 37.1484 | 61.7969 | 472.131 | 4551.02 |
PyTorch CPU: 
|    |    1e2 |     1e3 |    1e4 |     1e5 |      1e6 |      1e7 |
|----|--------|---------|--------|---------|----------|----------|
|  3 | 0.5915 |  0.6447 | 1.0245 |  7.629  |  57.9476 |  643.39  |
| …

PWGPP-581 N-dimensional histogramming benchmark

---

RootInteractive/Tools/Histograms/benchmark_histogramdd_pytorch.py
RootInteractive/Tools/Histograms/histogramdd_pytorch.py

This pull request(followup to #50) should:
-Change the way the benchmark is computed, from a hardcoded min of 20 values to a parametrizable min of means
-Improve the performance of histogramdd slightly
New benchmark results (CPU: Intel Core i5-6300HQ CPU @ 2.30 GHz, GPU: NVidia GeForce GTX 950M)
Numpy: 
|    |      1e2 |      1e3 |      1e4 |     1e5 |     1e6 |     1e7 |
|----|----------|----------|----------|---------|---------|---------|
|  3 |  0.2047  |  0.37234 |  1.29736 | 11.5826 | 160.307 | 1949.61 |
|  4 |  0.28856 |  0.4475  |  1.7853  | 15.6678 | 224.898 | 2679.14 |
|  5 |  3.26502 |  3.43916 |  5.05264 | 23.2    | 298.145 | 3563.87 |
|  6 | 35.536   | 36.0726  | 37.91    | 62.9623 | 446.907 | 4461.89 |
PyTorch CPU: 
|    |     1e2 |     1e3 |      1e4 |      1e5 |      1e6 | …

PWGPP-581 performance fixes

---

RootInteractive/InteractiveDrawing/bokeh/bokehDraw.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py

This PR fixes the compatibility of interactive drawing with Bokeh 2.2.3 by removing the deprecated CallbackPolicy field on sliders, fixing a JavaScript callback bug and fixing the line for updating the data source.
For some reason, the error bars are bigger than before on my machine, a hypothesis is that it's caused by the Bokeh update as the changes didn't touch the code responsible for that. - should be fixed by the last commit - was caused by error bar widths not being specified.

Compatibility bokeh

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py

This PR:
Adds debug messages to the JS callback measuring the time it took.
Refactors bokehDrawArray by changing color and marker to local variables, and removes optionLocal update in the inner loop as it doesn't do anything at all
Moves the creation of the color mapper out of the inner loop, making it no longer create a lot of redundant color mappers. This, in turn, speeds the test_bokehDrawSA test up by 25%, but it depends on the number of variables in each plot, the more variables with colZ defined the bigger the speedup.
Changes an "is not" to != to remove a warning.

Optimized bokehDrawArray

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR fixes multiselect to work with floats, but breaks its compatibility with strings in the CDS. Should also slightly improve the performance. Also changes the tests to reflect that.

Fixed multiselect to work with floats, no longer works with strings

---

RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.py
RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py

This PR adds histogram bin caching to the client-side histograms feature, optimizing the time needed to compute the histogram, resulting in a factor of something over 2 of improvement. The change to makeJSCallback adds a debug log that measures the time taken computing the histograms.

Client-side histogram - improved the performance slightly

---

RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts

This should improve the performance of histogramming, making it no longer take too much time. Performance gain of ~3x

Changed indices to nullable array instead of bokeh property in histogram

---

RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.py
RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogramWeight.py

This PR updates client-side histogramming using bokeh to the new interface in #90 and changes two tests to reflect it. This change is not backward compatible with the old interface in the 1D case, as it now accepts a sequence of floats as the range argument, which can be null for auto range, instead of accepting range_min and range_max.

Changing client-side histogramming to new interface

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_Compression.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py

This PR:
Changes test_Compression.py to use new histogram interface
Extracts more functions from bokehDrawArray
Implements the functionality to use multiple visualization types for 2D histograms. So far, the implemented ones are "heatmap" and "colZ" Example in test_bokehClientHistogram.py
Related to #90

Added colZ visualization for clientside histograms

---

RootInteractive/InteractiveDrawing/bokeh/CDSCompress.py
RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts
RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_Compression.py
RootInteractive/Tools/compressArray.py

Relates to #96
compression can be setup for each column separatelly
```
arrayCompressionRelative8=[(".*",[("relative",8), ("code",0), ("zip",0), ("base64",0)])]
xxx=bokehDrawSA.fromArray(df, "A>0", figureArray, widgetParams, layout=figureLayoutDesc, tooltips=tooltips,
widgetLayout=widgetLayoutDesc, nPointRender=200,arrayCompression=arrayCompressionRelative8)
```

Compression array - optional compression of CDS before sending to client (or saving) #96 

---

RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR:
bokehDrawArray and bokehDrawSA now remove unused columns and histograms from the resulting datasource that is sent to the client
Fixes a bug with widgets where they couldn't use derived variables

Remove unused columns

---

RootInteractive/InteractiveDrawing/bokeh/HistoStatsCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py

This PR:
Fixes a typo in the default tooltips for histograms
Adds a formatter option for histogram stats table - default is a precision of 3 decimals, with fixed notation between 1e-4 and 1e5
Removes the isOK row from the stats table in case columns are the histograms

Histogram stats table formatting

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py

When making the jupyter notebook, I have encountered a crash, running pytest has revealed that test_bokehClientHistogramWeight.py has failed because of a crash when generating the axi labels for 1D histogram. This PR should fix it.

Fixed a bug with auto axis titles causing crashes for some 1D histograms

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogramWeight.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
RootInteractive/Tools/compressArray.py

Relates to #137
This should fix two bugs in compressArray, one of them being an error handling bug that made the pipeline eat errors and continue with the array in a garbage state, the other bug was causing NaN values to crash when compression was used with used with "relative"

Fix for compression with NaN values

---

RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR adds:
ParameterArray, a new parameter to BokehDrawSA. So far, it can only be used to add widget control to color Z, but it is planned to be used in different ways in the future.
Example usage in test_bokehDrawSA.py
Additionally, in order to make this work, the pull request had to completely remake the logic of color mappers, ~partially breaking #148 and #146 by removing the dirty hack that made it work (histoND projection color mappers no longer ignore rows with NaNs for computing ranges, shouldn't be that difficult to fix by adding an extra JS callback)~ This got fixed in 
89d4670.
Fixes a bug making ND histogram auto ranges not work, and improves ND histogram performance slightly (can be improved further by changing the selection callback, performance is worse when ranges are …

Color Z widget

---

RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.py
RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogramWeight.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

Relates to #76 
This pull request:
Fixes a bug with imports in testBokehClientHistogramWeight.py - the test only worked because of a star import in bokehTools that was resulting in name collisions
bokehTools now only imports compressCDSPipe from Tools.compressArray - this was causing a weird bug, was probably supposed to be removed when the code was merged to master
Extracts downsampling code from makeJSCallback to its own bokeh extension, downsamplerCDS, and changed the downsampling algorithm to return predictable indices which are shuffled on initiation, possibly fixing #76 
I have encountered a weird bug when changing the displayed selection removed all selected points, the bug disappeared when inserting a breakpointand then they returned, the selected points were deselected, but I …

MakeJSCallback cleanup - extracting downsampling to custom bokeh model

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR adds legend options to parameter array, interface is same as in bokeh, see 
https://docs.bokeh.org/en/latest/docs/reference/models/annotations.html#legend
Work fully with parameters from parameterArray, test in test_bokehDrawSA.py
Relates to #157

Added legend options to parameter array

---

RootInteractive/InteractiveDrawing/bokeh/CDSCompress.py
RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_Compression.py

This PR fixes these 3 bugs:
Imports in test_Compression being wrong
DownsamplerCDS causing validation errors - filled the CDS with dummy data at the start
Compression not working if DownsamplerCDS present - regrassion caused by #159 this was caused by the data source for the downsampler being assigned cdsFull shadowing the real cdsCompress - reordering the lines to remove spaghetti code however caused it to not work because of having to downcast to ColumnarDataSource, this was fixed by changing the CDSCompress model.

Compression bugfix and footgun removal

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

Relates to #159, #156 and #121 
This is not a complete fix, as tooltips for ND histograms only work using the old interface. There is no need for the user to do anything, these tooltips are generated automatically.
This PR also fixes a bug introduced in #156 that caused the color bars to not get updated numbers and tickers when the color mappers got updated to a different variable and a bug introduced in #159 that made fields in tooltips not survive the downsampling process (and also the process that removed columns before they were sent to the client).

Auto tooltips for ND histogram projections

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.py
RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.py
RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.py
RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/bokehVisJS3DGraph.py
RootInteractive/InteractiveDrawing/bokeh/bokehVisJS3DGraph.ts
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR:
Fixes warning with pandas dataframes when a query parameter is provided to bokehDrawSA
Simplifies error bar logic, lowering file sizes in the process
Fixes a test in bokehDrawSA
Changes the base type to ColumnarDataSource for CDS types which have columns generated on the client - TODO: Add custom validation
Fixes #170

Removed error bar spaghetti and fixed some warnings

---

RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_Alias.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR:
Makes a non-breaking change to widget description array that makes the "default" and "callback" parameters optional by figuring the value out automatically
Refactors functions that make widgets by adding annotations
Adds a better error message for out of bounds default value with Select widgets
The default value of a Select widget can now also be specified as a string, in this case it uses the default value instead of the default index
Fixes a bug that was causing typescript compile errors
Relates to #171

Reduced widget description verbosity

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.py
RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/CDSJoin.py
RootInteractive/InteractiveDrawing/bokeh/CDSJoin.ts
RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_ClientSideJoin.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
RootInteractive/Tools/pandaTools.py

This pull request adds:
New parameter to bokehDrawArray - sourceArray
Outside of specifying histograms as in histoArray, it also allows specifying secondary data sources and joins on the client
Do not merge yet, case when histograms use sources different from primary CDS is broken, taking variables from secondary sources derived on server doesn't work either.
Use case:
```
df2 = pd.DataFrame(...)
sourceArray = [
{"name": "df2", "data": df2},
{"name": "join_df2", "left": None, "right":"df2", "left_on": ["bin_index"], "right_on": ["bin_index"], "how": "left"}
]
```

Clientside joins

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py

This PR adds the support of regular expressions to histoTable.
Usage:
```
figureArray = [
[['A'], ['histoA']],
[['A'], ['histoAB'], {"visualization_type": "colZ", "show_histogram_error": True}],
[['A'], ['histoAB'], {"yAxisTitle": "(A+B)/2"}],
[['B'], ['histoB'], {"flip_histogram_axes": True}],
["tableHisto", {"rowwise": False, "include": "histoA$|histoB$"}]
]
```

Added regular expressions to histoTable

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/compileVarName.py

This PR should fix #205 by raising a KeyError when an invalid column is used from a histogram.
However, a bug was discovered in joins when making the changes - columns in joins with implicit sources aren't added to the dependency tree - the fix for that bug is more complex, and the bug has a workaround by chaining table names with a dot, so it will probably be implemented in a later PR.
Possibly also fixes #121 by fixing inconsistent usage of "edges" between 1D and ND

Fixed error handling of nonexisting columns

---

RootInteractive/InteractiveDrawing/bokeh/MultiSelectFilter.py
RootInteractive/InteractiveDrawing/bokeh/MultiSelectFilter.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogramWeight.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
RootInteractive/Tools/compressArray.py

Should fix #210, also creates infrastructure for #193
This PR:
- Fixes a bug with compression causing it to only work with Pandas Series
- Adds caching of results for MultiSelect widgets
- Optimizes comparison for MultiSelect by replacing the reduce() with a for loop
- Optimizes it further by using bitmasks if the number of categories is not too large and fits within a 32-bit integer
TODO:
-Add the python function that makes a BitmaskMultiSelect widget

Optimized the MultiSelect widget selection

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR adds a new input parameter for widgets and figures, name, which can be used as a key in layoutDesc (whether widgets or figures) See test_bokehDrawSA.py
Relates to #199
Also makes error handling for nonexistent columns less cryptic by sending CDS names to the client, and removes the boxess from heatmaps (copypasted from #209)

Widgets in layoutDesc can be found by names

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts
RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogramWeight.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR:
- Adds an "index" parameter for range sliders. Points outside the range are not considered for the selection. The column for it must be sorted, but it improves performance. Possible smarter indexing in future PR
- Adds an "index" column to data sources if not specified - not sure if it should be kept, ambiguous requirements
- Optimizes auto ranges in histograms
- Removes bin caching in ND histograms with auto ranges - in some use cases leads to improved performance
- Changes Float32Arrays in CDSCompress to normal arrays - seems to improve the performance

MakeJSCallback index slider, performance optimizations

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py

This PR:
- fixes a bug where selections for multi-selects are invalidated when an unrelated derived column change - bokehTools.py - the bug was introduced in #212
- Adds a simple dependency tree for derived columns on the client, optimizing recomputing them as a side effect by saving some garbage collection time - CDSAlias.ts - this should also make derived columns update properly when dependencies are changed, preparation for making the text input widgets as discussed in ATO-595
* Fix problem with suboptimal performance of parametric aliases - reported in ALICE fastCombinator tracking use case 
* https://alice.its.cern.ch/jira/browse/ATO-595
* avoid multiple updates  (1 update instead of the ~ 10 updates - number of multi-select widgets in dashboard)

MultiSelect optimization/bugfix

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_Alias.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR:
-Adds a test for custom JS function text input - test_Alias.py
-Fixes bugs preventing it from working - seems that for some reason, it was already mostly implemented, and the only changes needed were fixing a broken 2-line JS callback, and creating the text input widget itself.
Fixes #229 
How to use:
In widget array, create a "text" widget, where the relevant argument is parameter name
```
aliasArray=[
{
"name": "custom_column",
"variables": ["A", "B", "C", "A_mul_paramX_plus_B"],
"func": "CustomFunc"
}
]
parameterArray=[
{"name": "CustomFunc", "value":"return Math.sin(A_mul_paramX_plus_B)"}
]
widgetParams=[
...,
['text', ["CustomFunc"]],
....
]
```
Screenshot of result:

Custom JS function text input

---

RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts
RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts

This PR fixes the behavior of N-dimensional histograms in some edge cases by:
- Making the top edge of the top bin inclusive correctly, before it was off by one
- Adding a workaround to auto ranges when min == max by decrementing min and incrementing max - to prevent division by zero

Histogram edge case with auto ranges fix

---

RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py

This PR:
- Allows modifying histogram ranges and number of bins on the client using parameterArray
- Fixes a bug with ND histogram where it wasn't updating the length correctly (as the length was never updated in any use case, the bug wasn't really a bug before the nbins parameter was added)
- Fixes a bug in the downsampler with changing input sizes (before this change, it was an edge case, this change made it visible)
- Slightly optimizes the dependency tree by not adding the pre-transformation multiSelect columns
- in test_bokehClientHistogram.py fixes the output file name for test_bokehClientHistogram3d
- Fixes a bug caused in #172 causing widgetArray to sometimes get modified in place
- was there   since Nov 20, 2021, but this fragment of code not used until text input for selection …

Histogram ranges / number of bins widgets

---

RootInteractive/InteractiveDrawing/bokeh/RangeFilter.py
RootInteractive/InteractiveDrawing/bokeh/RangeFilter.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR:
- Reverts the color mapper minimum change from #230 - bins with entries below 1 not being drawn caused side effects if color axis was used for anything that could take values less than 1
- Adds the "toggleable" option to slider and select widgets- not supported for MultiSelect widgets as disabled option is not supported for them
- Refactors makeJSCallback - more preparations to replace with a smarter solution
- Adds support for spinner widgets - so far they can only control parameters in parameterArray

Toggleable widgets

---

RootInteractive/InteractiveDrawing/bokeh/MultiSelectFilter.py
RootInteractive/InteractiveDrawing/bokeh/MultiSelectFilter.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR adds a new widget - spinnerRange
The widget consists of two spinners, with step size so far hardcoded to be 5% of max-min - this can be changed but there might be technical issues
This PR also refactors the select widget, removing it from makeJSCallback, only leaving the logic for textinput there
Example use in test_bokehDrawSA.py
```
widgetParams=[
['spinnerRange', ['C']]
]
```

Spinner range widget

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR:
- Fixes spinner range not working with Python 3.8 because of unbound variable error
- Removes convoluted bitmask based logic from the select widget (now uses a simple comparison)

Spinner range bugfix

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.py
RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.py
RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.py
RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts
RootInteractive/InteractiveDrawing/bokeh/HistoStatsCDS.py
RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.py
RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehVisJS3DGraph.py

This PR introduces back-compatibility breaking changes that allow migration to bokeh 2.4.1 as of today the newest version. It also changes the requirements.txt and setup.py files to reflect that change.
The migration to a new version of bokeh seems to have resulted in better performance, changing the selection in test_bokehClientHistogramWeight got reduced from 200ms to 150ms on my machine. Other clientside benchmarks to be tested soon.
EDIT: Seems that it still works with bokeh 2.3.0, doesn't work with previous versions of bokeh

Migration to bokeh 2.3.3

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/compileVarName.py
RootInteractive/InteractiveDrawing/bokeh/test_Alias.py

This PR:
-Fixes a bug that made aliases with no input variables crash
-Adds anonymous custom JS expressions - example:
```
figureArray=[
[['bin_center'], ['eff_isOK', 'isOK / bin_count'], {"source":"histoA", "size":"size", "errY":"sqrt(isOK)/bin_count"}],
]
```
Supported expressions:
Binary operations - add, sub, mult, div, mod, lshift, rshift, or, xor, and
Numpy ufuncs / javascript Math functions - sin, cos, arcsin, arccos, arctan, exp, log, log2, log10, sqrt, abs, sinh, cosh, arcsinh, arccosh, arctan2
Unary operations - uadd, usub, not
Comparators (Python style, converted to Javascript style) - ==, !=, <, <=, >, >=
Parameters in parameterArray
WISH:
- Add support for reducers (sum, mean, std, subscript, ...)

Anonymous custom JS expressions

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_Alias.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py

This PR:
- Refactors bokehDrawArray by extracting a method
- Adds an "expr" parameter to aliases - takes a string input which is converted to javascript and has auto detected input parameters
- Adds a less verbose interface for aliases - a (name, expr, table) tuple - examples in test_bokehClientHistogram.py and test_Alias.py
Simple example
```python
aliasArray=[
("errX", "sqrt(X)"),
("logX", "log(X)")
]
```
Example using loop
```python
aliasArray = [
(f"{i}_normed", f"{i} / bin_center_0**2", j) 
for i in ["mean", "std", "quantile_0", "quantile_1", "quantile_2"]
for j in ["histoAB_1", "histoABWeight_1", "projectionA", "projectionAWeight"]
] 
```

Less verbose aliasArray interface

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts
RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py

This PR:
- Adds "cumulative" and "density" options to 1D histograms
-- Cumulative: take the inclusive cumulative histogram
-- Density: Divide by bin width and total (only total if taking cumulative histogram)
- Adds "cumulative" and "cdf" columns to projections
- Fixes a bug causing aliases to not work with javascript math functions - a quick workaround before the real fix can be applied in #256

Cumulative histogram

---

RootInteractive/InteractiveDrawing/bokeh/ConcatenatedString.py
RootInteractive/InteractiveDrawing/bokeh/ConcatenatedString.ts
RootInteractive/InteractiveDrawing/bokeh/CustomJSNAryFunction.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/compileVarName.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

Because of bokeh technical limitations, changing axis scales is not possible without making large changes. However, if changing the tickers and inverting the transform isn't needed, this PR adds a workaround.
This PR:
- Adds a parameter for bokehDrawArray in figureArray - "y_transform" - takes the transformation applied to it Can be either None for the identity transform, a parameter in parameterArray or a string which is interpreted as an expression to use.
- Optimizes bin caching for ND histograms by adding array pooling
Example:
```python
parameterArray=[
{'name':"transformY", "value":None, "options":[None, "sqrt", "lambda x: log(x+1)"]}
]
figureArray=[
[['bin_center_0'], ['bin_count'], {"colorZvar":"bin_center_1", "errY": "sqrt(bin_count)", "source":"histoAB", …
```

Y-Axis transforms (#254, #247)

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts

1 liner change to javascript to support parameters in custom functions that can be either scalars or vectors - better implementation to be added later.

Added support for the '1' alias

---

RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts
RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts
RootInteractive/InteractiveDrawing/bokeh/test_Compression.py
RootInteractive/Tools/compressArray.py

This PR:
-Makes infinite values not count for auto ranges in histograms
-Removes NaN when computing mean and std
-Simplifies the interface for array compression - TODO: remove the need for "base64" at the end and ignore if it's specified as the last step for back compatibility reasons

NaN handling in histograms, simplified compression insterface

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/compileVarName.py
RootInteractive/Tools/compressArray.py

This PR:
- Makes CDSCompress use base64 encoding even if not explicitly specified inarrayCompression (before, it would crash)
- Fixes #283
- Arctan2 - was a missing comma
- Unit - spaghetti code, after refactoring reason became clear, in this case the CDS was accessed before it was created

Automatically add base64 to arrayCompression, fix for parsing call with more than 1 parameter #283

---

RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts
RootInteractive/InteractiveDrawing/bokeh/RangeFilter.ts
RootInteractive/Tools/RDataFrame/RDataFrame_Array.py

This PR:
-Adds error handling to range filters in javascript, console logging a warning if the range is empty
-Adds support for global functions and arrays of arrays in makeDefine
Example:
```python
makeDefine("C","cos(A[1:10])-B[:20:2,1:3]", None,3, True)
```
Output
Implementation:
```c++
auto C(){
RVec<RVec<double>> result(10);
for(size_t i=0; i<10; i++){
RVec<double> result_1(2);
for(size_t i_1=0; i_1<2; i_1++){
result_1[i_1] = (cos(A[1+i*1])) - (B[0+i*2][1+i_1*1]);
}
result[i] = result_1;
}
}
```
Dependencies
['B', 'A']

Rdataframe makeDefine

---

RootInteractive/InteractiveDrawing/bokeh/compileVarName.py
RootInteractive/Tools/RDataFrame/RDataFrame_Array.py
RootInteractive/Tools/RDataFrame/test_RDataFrame_Array.py

This PR:
- Fixes a bug with loop variable bounds being wrong because of a wrong sign (RDataFrame)
- Adds support for detecting output type using a dictionary of types (RDataFrame)
- Fixes the behavior of TrueDiv in case integers are used by casting to float (RDataFrame)
- Adds support for FloorDiv and Invert in expressions for bokehDraw (JavaScript)

makeDefine support for detecting output type -> #293

---

RootInteractive/InteractiveDrawing/bokeh/ColumnFilter.py
RootInteractive/InteractiveDrawing/bokeh/ColumnFilter.ts
RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.py
RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.ts
RootInteractive/InteractiveDrawing/bokeh/LazyIntersectionFilter.py
RootInteractive/InteractiveDrawing/bokeh/LazyIntersectionFilter.ts
RootInteractive/InteractiveDrawing/bokeh/MultiSelectFilter.py
RootInteractive/InteractiveDrawing/bokeh/MultiSelectFilter.ts
RootInteractive/InteractiveDrawing/bokeh/RIFilter.py
RootInteractive/InteractiveDrawing/bokeh/RIFilter.ts
RootInteractive/InteractiveDrawing/bokeh/RangeFilter.py
RootInteractive/InteractiveDrawing/bokeh/RangeFilter.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py

This PR:
- Fixes various bugs in makeJSCallback negatively affecting performance
- - test_bokehClientHistogram.py - 5 widgets, 5e6 points, time for selecting points went from 300ms to 60ms
- - ATO-609/trackClusterDumpDraw.ipynb -  3e6 points, 8 widgets, time for selecting points went from 240ms to 60ms
- Fixes a bug with plot title when using custom axis titles
- Fixes a crash that sometimes happens when downsampler is initialized (couldn't reliably reproduce)

makeJSCallback optimization and bugfixes

---

requirements.txt
setup.py

Recently, I get the following error when installing RootInteractive with pip, using pip-23.0.1
```
Collecting sklearn
Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [18 lines of output]
The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
rather than 'sklearn' for pip commands.
Here is how to fix this error in the main use cases:
- use 'pip install scikit-learn' rather than 'pip install sklearn'
- replace 'sklearn' by 'scikit-learn' in your pip requirements files
(requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
- if the 'sklearn' package is used by one of your …
```

Replacing deprecated sklearn with scikit-learn

---

RootInteractive/MLpipeline/MIForestErrPDF.py

This PR:
-Speeds up predictRFStat by making median/quantile/std parallel
-Reduces memory consumption of predictRFStat by adding a max_rows parameter that splits it into multiple parts to avoid expanding the whole array

Predict rf stat

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/ClientLinearFitter.py
RootInteractive/InteractiveDrawing/bokeh/ClientLinearFitter.ts
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_Alias.py
RootInteractive/InteractiveDrawing/bokeh/test_ClientSideJoin.py
RootInteractive/MLpipeline/MIForestErrPDF.py

This PR adds linear regression on the client to RootInteractive.
This PR also:
- Enables using multiselect for parameters
- Fixes an infinite loop in javascript in case of cyclic dependency between custom defined columns
This isn't finished, and some features are missing:
- fitterArray to automatically create aliases, without having to use transformArray and aliasArray
How to use
```Python3
parameterArray = [
{"name": "predictors", "value":["X1","X2"], "options":["X1", "X2", "X3",  "Custom"]}
]
jsFunctionArray = [
{
"name": "fitterY",
"type": "linearFit",
"varX": "predictors",
"varY": "Y",
"alpha": 1,
"weights":"W",
"source": None # If using the main source for fitting, this is optional
}
]
aliasArray = [
{
"name": "YPred",
"variables": "predictors",
"transform": "fitterY"
}
] …
```

Linear fitter on the client

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/bokehInteractiveTemplate.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py

This PR adds multiselect varY / varYNorm for the getDefaultVars template
Because "varY-varYNorm" alias is not defined when one of these is a multiselect, it's done by creating multiple histograms and then creating the join, in the template
It also fixes a bug with the Y axis label introduced in #326, a bug making getDefaultVarsRatio also introduced in #326 not work because of a typo and an old bug with scalar histogram weights (possibly never worked properly)
Multiselect varZ / varZNorm not supported for template yet
Example use cases in test_bokehClientHistogram.py

Multiselect varY / varYNorm template

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/CustomJSNAryFunction.py
RootInteractive/InteractiveDrawing/bokeh/LazyIntersectionFilter.ts
RootInteractive/InteractiveDrawing/bokeh/bokehInteractiveTemplate.py
RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/Tools/aliTreePlayer.py

This PR:
- Fixes funCustom when using the template and specifying anonymous functions as variables, before it just crashed by parsing the input with a regex
- Optimizes lazy evaluation when selection formally changes but no actual change happens, at the cost of slightly slowing down evaluation otherwise (factor 4 speedup in usual use case)
- Optimizes swapping out a function used by multiple columns (factor 2 speedup when changing diff function in getDefaultVarsNormAll)
- Removes compute_functions() function as it's not used anywhere
- Fixes warnings in aliTreePlayer.py

Various client side lazy evaluation optimizations and bugfix

---

RootInteractive/Tools/RDataFrame/RDataFrame_Array.py
RootInteractive/Tools/RDataFrame/RollingSum.cpp
RootInteractive/Tools/RDataFrame/test_RDataFrame_Array.py

This PR adds support for rolling window statistics in the RDataFrame interface 
To do: Add rolling median, fix inconsistent window width input parameter for time series index, add rolling variance support for time series index
Example in test_RDataFrame_Array.py

Rolling window statistics - so far only sum, mean and std

---

RootInteractive/Tools/RDataFrame/RDataFrame_Array.py
RootInteractive/Tools/RDataFrame/RollingQuantile.cpp
RootInteractive/Tools/RDataFrame/RollingSum.cpp
RootInteractive/Tools/RDataFrame/test_RDataFrame_Array.py

This PR implements rolling median for RDataFrame, so far only a slow, brute force version that uses bubble sort - should be enough for small window sizes

Rolling median builtin for domain specific language with RDataFrame

---

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts

This PR fixes a bug introduced in #336 causing changing the diff function to not invalidate the cached values if the diff function is used in multiple places. This bug was already caught by a test, test_bokehClientHistogram.py::test_interactiveTemplateMultiYDiff 
This PR also optimizes computing projections from histograms by preventing a sparse array from being created.

Bugfix for caching functions on the client used multiple times (introduced in #336, mentioned in #340)

---

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py

This PR removes uproot dependency from bokehDrawSA.py - it was caused by a star import that didn't have to be there

Removed uproot dependency

---

RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts
RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts

This PR:
- Probably fixes a bug with uninitialized bin caching in ND histograms, not 100% sure as I can't reproduce it reliably, it's also a hacky workaround and a more permanent fix will follow soon
- Fixes a bug with HistoNdProfile leaking a compute heavy data dependency in case of multiple weights, optimizing by a factor that scales with the number of histograms, but usually 2x-3x
- Optimizes histogram auto ranges by removing Math.min() and Math.max(), forgot to check time before change
- Changes iteration order in ND histogram from row major to column major, this change improves the performance of the histogram by 30%

HistoNdProfile data dependency leak fix
