miranov25/RootInteractive

InteractiveDrawing/bokeh/bokehDraw.py, InteractiveDrawing/bokeh/bokehDrawPanda.py, InteractiveDrawing/bokeh/bokehTools.py, MLpipeline/NDFunctionInterface.py, Tools/aliTreePlayer.py, tutorial/distortionCase/distortionStudy.py
=> Python2 -> Python3

InteractiveDrawing/bokeh/bokehTools.py, Tools/aliTreePlayer.py
* It was iterated through a dictionary while its structure is changing during iteration. Solved by creating pop lists.
* fig.plot_width = int(option["plot_width"]) / nCols was interpreted as float. Solved by shifting the bracket.
Only one error left due to missing data.
=> Errors in the code due to Python2->Python3 transition debugged.

RootInteractive/InteractiveDrawing/bokeh/bokehDraw.py, RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py, RootInteractive/Tools/test_histoNDTools.py
for
- RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
New test functions for drawing from Tree is implemented
for 
RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
RootInteractive/InteractiveDrawing/bokeh/bokehDraw.py
a bug about the options of tree drawing is fixed
=>  pytest for tree drawing for standalone via Figure Array

RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py, RootInteractive/Tools/test_histoNDTools.py, tutorial/bokehDraw/bokehTreeDrawSA.ipynb
-All widgets are implemented in SA
-All widgets except Checkbox are working properly
-When Checkbox is enabled, output html file  becomes blank.
-test_histoNDTools.py is modified to use data from webserver only...
=> Other widgets have been implemented

RootInteractive/Tools/histogramND.py, RootInteractive/Tools/test_histoNDTools.py, RootInteractive/Tools/test_histogramND.py
RootInteractive/Tools/histogramND.py :
- draw2D:  axis titles, color bar and tooltips are implemented
- draw1D:  implemented but NOT WORKING for now..
=> histogramND draw2D :options

RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py, RootInteractive/Tools/histogramND.py, RootInteractive/Tools/test_histoNDTools.py
for:
- RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
- RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
- RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
MultiSelect widget has been implemented
for:
- RootInteractive/Tools/histogramND.py
1D histogram has been fixed
for:
-  RootInteractive/Tools/test_histoNDTools.py
minor clean-up
=> Multi select & 1D histogram

.idea/RootInteractive.iml, .idea/workspace.xml, RootInteractive/InteractiveDrawing/bokeh/test_bokehDraw.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawArray.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py, RootInteractive/TTreeHnInteractive/TTreeHnBrowser.py, RootInteractive/Tools/aliTreePlayer.py, RootInteractive/Tools/histoNDTools.py, RootInteractive/Tools/makePDFMaps.py, RootInteractive/Tools/test_aliTreePlayer.py, RootInteractive/Tools/test_histoNDTools.py, RootInteractive/Tools/test_histogramND.py, RootInteractive/Tools/test_makePDFMaps.ipynb, RootInteractive/tutorial/bokehDraw/bokehDrawArray.ipynb, RootInteractive/tutorial/distortionCase/pandaTools/distortionDraw.ipynb, RootInteractive/tutorial/distortionCase/test_Distortion.py
The median algorithm is changed and comments to explain code are added
=> median algorithm is changed with a faster one

RootInteractive/Tools/Histograms/histogramdd.py, RootInteractive/Tools/histoNDTools.py, RootInteractive/Tools/histogramND.py, RootInteractive/Tools/test_makePDFMaps.py
This PR:
Adds an implementation of histogramdd using PyTorch, which should run faster than the numpy implementation because of vectorized searchsorted
(Will add the unit tests soon)
Fixes a typo in a HistoNDTools error message
=> PWGPP-581 N-dimensional histogramming using Pytorch

RootInteractive/Tools/Histograms/benchmark_histogramdd_pytorch.py, RootInteractive/Tools/Histograms/histogramdd_pytorch.py, RootInteractive/Tools/Histograms/test_torchHistogramdd.py, RootInteractive/Tools/histoNDTools.py, RootInteractive/Tools/test_makePDFMaps.py
This PR:
-Renames the N-dimensional histogramming pytorch script to a more descriptive name
-Adds documentation for the function
-Adds unit tests
-Fixes some bugs revealed by the unit tests
=> PWGPP-581 N-dimensional histogramming unit tests

RootInteractive/Tools/Histograms/benchmark_histogramdd_pytorch.py, RootInteractive/Tools/Histograms/histogramdd_pytorch.py, RootInteractive/Tools/Histograms/test_torchHistogramdd.py
This PR:
Fixes a typo in benchmark output
Fixes a bug that makes histogramming crash with uniform binning when device isn't default device
Adds device as a parameter to the tests
=> PWGPP-581 added GPU tests, fixed a bug that happens when bins is a sequence of ints and device isn't the default device

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
Should solve: #53 
This doesn't use Band and instead uses VBar, but it solves the issue by making the error bars properly interactive. So far it only works for errY and not errX.
=> PWGPP-548 error bars

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
As in issue #53 the color of the error bnars shoul;d be fixed.
=> PWGPP-548 Changed the color of the error bars to match the markers

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
Solves #53 and PWGPP-548
This PR adds error bars in the X-axis, and modifies one test to use these error bars.
=> PWGPP-548 added X error bars

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
This PR enables specifying the varZ option for bokehDrawArray, doesn't support many features yet, will be added soon.
=> Initial integration of visJS graph3d within bokehDrawArray

RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
This PR:
Adds random downsampling to the JS callback, the number of points to render is a parameter to bokehDrawSA
Changes the callback policy on sliders from continuous to mouseUp
Adds a test for downsampling\
Related to #76
=> Added downsampling to JS callback

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
For some reason, this didn't make it to the last pull request. This fixes a major bug with the JS callback that makes it both run slow and breaks the cdsSel.
=> Fixed downsample indexing being inconsistent

RootInteractive/InteractiveDrawing/bokeh/bokehDraw.py, RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawArray.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
Fixes #80 
Rescaling is done in the big JS callback, can extract that into a separate method later.
Changes bokehTools(the major change), bokehDrawSA(color mapper), test_bokehDrawSA(the third plot now tests this change), and test_bokehDrawArray(so that it still runs with the minor change to the interface)
=> Refactored makeJSCallback and optimized it, added color mapper rescaling

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
Partially fixes #86 - the widgets in the test work properly for me.
Only touches the code in the cases for select and multiSelect, which already made the tests work for me, please test that on your machine too.
=> Fixed JS callback to work with booleans in select/MultiSelect

RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.py, RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts, RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
Partially fixes #90
This adds a custom CDS that is updated client-side whenever its source is updated to reflect its histogram, and in bokehDrawArray, using "histo" as the Y variable will plot the histogram out. Example usage in RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
=> Added client side histogramming using JavaScript

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogramWeight.py
This should improve the performance of clientside histogram further, by removing unnecessary work from it.
=> bokehDrawArray no longer outputs cdsSel if nothing draws from it

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
This fixes the bug where using client side histogram with varX specified as a function didn't work.
=> histograms can be used with varX specified as a function

RootInteractive/InteractiveDrawing/bokeh/Histo2dCDS.py, RootInteractive/InteractiveDrawing/bokeh/Histo2dCDS.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
This adds 2D histogramming to bokehDrawArray - so far it only uses the old interface. To use it, specify "histo2d":True in the options.
=> Added client-side 2D histogram

RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogramWeight.py, RootInteractive/InteractiveDrawing/bokeh/test_surface3d.py
#104 but to master instead of miranov25/cleanup. Related to #100 
This removes drawColzArray from bokehTools.py, removes the old interface for histograms from bokehDrawArray, and fixes two tests that would otherwise fail.
=> More cleanup

RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
=> Added error bars to 1D histograms

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/bokehVisJS3DGraph.py, RootInteractive/InteractiveDrawing/bokeh/bokehVisJS3DGraph.ts, RootInteractive/InteractiveDrawing/bokeh/test_Compression.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py, RootInteractive/Tools/compressArray.py
* adding CDSCompressy.py and CDScompress.ts - NOT YET working
* Compression as pipeline of action implemented RootInteractive/Tools/compressArray.py
* Unit test  RootInteractive/InteractiveDrawing/bokeh/test_Compression.py
* cat test_Compression.py | grep -P "(def test_|actionArray=)"
```
def test_CompressionSequence0(arraySize=10000):
actionArray=[("zip",0), ("base64",0), ("debase64",0),("unzip","int8")]
def test_CompressionSequenceRel(arraySize=255,nBits=5):
actionArray=[("relative",nBits), ("zip",0), ("base64",0), ("debase64",0),("unzip","int8")]
def test_CompressionSequenceAbs(arraySize=255,delta=0.1):
actionArray=[("delta",delta), ("zip",0), ("base64",0), ("debase64",0),("unzip","int8")]
def test_CompressionSample0(arraySize=10000,scale=255):
actionArray=[("zip",0), ("base64",0), …
```
=> Array compression as a pipeline of actions

RootInteractive/InteractiveDrawing/bokeh/CDSCompress.py, RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts
Forgotten to add in previous commit
=> #96 - adding compression CDS -not WORKING yet

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogramWeight.py
This should result in much smaller file sizes being sent to the client.
=> Fixed a bug causing compression to not work with histograms present

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
Fixes #115 
One liner fix to a bug caused by random indices not being multiplied by nPointsRender.
=> Fixed a downsampling bug

RootInteractive/InteractiveDrawing/bokeh/Histo2dCDS.ts, RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
This fixes the auto ranged for 1
D histograms, also fixes some memory leaks on the client.
=> Histogram auto ranges

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
This adds tooltips to histograms, the tooltips arrays can be specified globally, per figure or per histogram, the per histogram tooltips take priority over the per figure tooltip settings.
=> Added tooltips to histograms

RootInteractive/InteractiveDrawing/bokeh/HistoStatsCDS.py, RootInteractive/InteractiveDrawing/bokeh/HistoStatsCDS.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
This adds quantiles to histoStatsCDS and its corresponding tables, interface is "quantiles" keyword in histoArray, so far it just merges the arrays and uses all of them for each 1D histogram.
=> Added quantiles to histoStatsCDS

RootInteractive/InteractiveDrawing/bokeh/HistoStatsCDS.py, RootInteractive/InteractiveDrawing/bokeh/HistoStatsCDS.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
Should fix part of #123 but this is just a prototype, still working on fixing the bugs with outputting NaN when either range end coincides with the upper bound of histogram's range
=> #123 added sum in user defined ranges

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
This one-liner PR fixes the bug with colorZvar not being added to the dictionary and therefore not sent to the client.
=> Fixed bug with colorZvar not being sent to client

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
=> Fixed default markers

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/tutorial/bokehDraw/test_bokehClientHistogram.ipynb
This PR:
Fixes a bug with histogram weights using wrong column names
Adds a tutorial for the ND histogram feature
=> Histond tutorial

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
This PR fixes a bug with tabs in bokehDrawArray, and adds a test for in in test_bokehDrawSA.py
=> Fix for figure tabs

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.py, RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts, RootInteractive/InteractiveDrawing/bokeh/CustomJSNAryFunction.py, RootInteractive/InteractiveDrawing/bokeh/CustomJSNAryFunction.ts, RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.ts, RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts, RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.py, RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts, RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_Alias.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py, RootInteractive/tutorial/bokehDraw/standAlone.ipynb
This PR adds support for custom JS functions in bokehDrawArray computed on the client either on the histograms or the main CDS.
=> Client side functions and efficiencies

RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts, RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.ts, RootInteractive/Tools/compressArray.py, RootInteractive/tutorial/bokehDraw/customJsColumns.ipynb, RootInteractive/tutorial/bokehDraw/standAlone.ipynb
This PR:
* Fixes a bug in downsampling causing points to sometimes get deselected
* Fixes a bug with NaN values in compression thought to be fixed in #144 that was actually still there, just not noticed because the test was broken and passing when it shouldn't
* Updates the outdated standAlone.ipynb jupyter notebook to use the new interface
* Adds a new jupyter notebook tutorial, customJsColumns.ipynb with custom JS columns on the client
=> Tutorials for bokehDrawSA and client side functions

RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.py, RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.py, RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, docs/source/RootInteractive.InteractiveDrawing.bokeh.rst
This PR fixes some mistakes in the documentation, more in-depth fixes to follow later
=> Minor documentation fixes

RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py, tests/README.md
First test version of the PyTest with regression test and JSON report for further time series analysis
=> Pull request - PyTest - Regression test and json/xml for later processing #177 (part 0)

RootInteractive/InteractiveDrawing/bokeh/test_Compression.py, tests/README.md, tests/pytest.sh, tests/pytestJSON.py
Example usage:
```
aingularity> makePyTest 4 testGSI4 /lustre/alice/users/miranov/tests/RootInteractive ""
makePyTest
Parameters:
1.) param 4 - testWorkers  - number of workers to test
2.) param testGSI4 - testName
3.) param /lustre/alice/users/miranov/tests/RootInteractive - testPrefixServer
4.) param  - testServer
```
makePyTest 4 testGSI4 /lustre/alice/users/miranov/tests/RootInteractive ""
makePyTest 32 testGSI32 /lustre/alice/users/miranov/tests/RootInteractive ""
=> Pytest adding pytest server to store performance data as json reports  

RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
This PR:
-Fixes the TextAreaInput widget, now it works again
-Refactors makeJSCallback
=> TextAreaInput widget fix

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
This PR:
-Adds a "toggle" widget to the widgetArray - used in test_bokehDrawSA.py to toggle legend visibility
-Number of points to show for downsampler can be changed with a parameter - slider to do that s used in test_bokehDrawSA.py
=> Added simple to add visualization parameters

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
Added option to use heatmap drawing when source option is used. This enables the transformation of the color axis in 2D histogramming (doesn't work with transformations on the x and y axis). Also, the hover tool doesn't work when this option is used.
Also hard coded that bins with entries below 1 are not drawn (should be parametrized probably)
=> Heatmap with source

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_Compression.py, RootInteractive/Tools/compressArray.py
Fixes #232 and its duplicate #244 by converting int64 columns to either int32 or float depending on which is safer
=> Int64 compression bugfix

RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/compileVarName.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
This PR adds a new interface for heatmap visualization of histograms, partially implementing #248
Asymmetric error bars seem harder to implement than originally thought, as it would possibly require some way of either making subexpression hashes that are valid javascript variable names, refactoring some of the javascript, or creating a custom error bar glyph that is just a bokeh quad in the background.
=> Heatmap tuple interface

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
=> Asymmetric error bars

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
This PR:
- Fixes a bug with auto axis titles being incorrect for heatmaps introduced in 81313e3
- Adds support for axis transform new interface to the X axis, previously only worked for the Y axis
=> X axis transform

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
This PR adds two options for spinners
-Relative step size
-Formatting - uses the interface from https://numbrojs.com/format.htm
-Also has detection for printf format strings
-TODO: Add support for %g printf style formatting
=> Spinner ranges formatting and step size --> #259

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
=> Custom function freezing bugfix

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts, RootInteractive/InteractiveDrawing/bokeh/CustomJSNAryFunction.ts
This PR:
-Adds data_source parameter to aliases
-Improves performances for aliases specified using v_func
=> Added workaround + optimization for aliases

RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py
Relates to #262
This should improve the performance, in test_UnbinnedQuantile it improved the time from 33 seconds to 15 seconds. Bottlenecks still seem to be validation, compiling typescript and compression.
=> Optimized bokehDrawSA by removing dead code

RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
This PR:
-Instead of endless loop, a javascript exception is raised when quantiles are not sorted - relates to #272
-Adds color axis to default plot title
=> Color axis added to plot title

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py
This PR adds support for parameters in axis transforms.
Before: parameters only worked if there was only one axis transform - was a case of the JS callback modifying the wrong value
=> Parametrized transforms

RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts, RootInteractive/InteractiveDrawing/bokeh/compileVarName.py
This PR:
- Allows the use of select widgets for variables in anonymous expressions - TODO: Do this also for aliases
- Fixes an infinite loop in unweighted quantiles if the interval consists of all NaN
=> Using parameters in expressions

RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_Compression.py, RootInteractive/Tools/compressArray.py, RootInteractive/Tools/histoNDTools.py, RootInteractive/Tools/histogramND.py, RootInteractive/Tools/test_makePDFMaps.py
This PR improves the efficiency of compression by
- Downgrading the type (float32 if safe for relative rounding, smallest integer type that fits the whole array for absolute rounding)
- Adding lazy loading of columns on the client
Observed results in test_Compression.py (1 million points)
Relative rounding: CPU time on server reduced by 50%, file size reduced by 10%, CPU time for decompression unchanged
Absolute rounding: CPU time on server reduced by 70%, file size reduced by 20%, forgot to measure CPU time on client for decompression
=> Optimized compression

RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts, RootInteractive/Tools/compressArray.py
This PR:
- Fixes a bug in CDSCompress.ts causing decompression to not work if old interface is used
- Adds another verbosity option in compressArray
=> Compression bugfix

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.py, RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
This PR:
-Refactors bokehDrawArray by removing a hacky workaround
-May fix the bug Tuba reported (will test soon)
=> Changed aliasDict in makeJSCallback hacky workaround to the intended way

RootInteractive/InteractiveDrawing/bokeh/ColumnFilter.py, RootInteractive/InteractiveDrawing/bokeh/ColumnFilter.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/compileVarName.py, RootInteractive/InteractiveDrawing/bokeh/test_Alias.py
This PR:
- Optimizes text input selection widget by caching the computed result
- If variables are not specified for custom JS function in aliasArray, all variables are used (except for these that would cause a cyclic dependency)
=> Optimization for custom filter using text input

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
This PR:
-Adds a div widget for inserting HTML
-Adds  automatically generated description table using meta
Related to #309
=> Div widget and table to describe data (parsing user input  metadata) - for #309

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
This PR:
-Fixes #313 
-Adds a test for a column of all ones with spinnerRange to test_bokehDrawSA.py
=> Fix for #313

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
This PR:
-Adds change callback to selection table for expression
-Adds CDS name field to selectionTable
-Changes descriptionTable from raw HTML div to a DataTable
=> descriptionTable change to bokeh DataTable

RootInteractive/InteractiveDrawing/bokeh/CDSStack.ts, RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.py, RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
This PR:
-Optimizes multiselect weights for projections
-Disables color bar labels, will be reenabled after updating to new bokeh version
-   option - showColorAxisTitle
=> Optimized multiselect weights

RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts, RootInteractive/InteractiveDrawing/bokeh/bokehInteractiveTemplate.py, RootInteractive/InteractiveDrawing/bokeh/doc/READMEtemplate.md, RootInteractive/Tools/RDataFrame/RDataFrame_Array.py
Relates to #297 
To add: documentation for new template
=> Template bugfixes and support for function in namespace

RootInteractive/InteractiveDrawing/bokeh/bokehInteractiveTemplate.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py, RootInteractive/Tools/RDataFrame/RDataFrame_Array.py, RootInteractive/Tools/RDataFrame/test_RDataFrame_Array.py
This PR:
-Adds support for multiselect varY with toggleable diff function
- Adds support forprojections in the RDataFrame interface
=> Template switchable

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_Alias.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
Fixes #332 
Adds unit test to test_bokehDrawSA.py
=> #332 added better error handling for invalid widgets

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts
Fixes #338, which possibly is a duplicate of another issue
=> Error handling for custom variables

RootInteractive/InteractiveDrawing/bokeh/CDSStack.ts, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py
This PR partially fixes a bug with joins on client introduced in #326 that's making them slow by adding an early return
=> Optimization for simple joins on client

RootInteractive/InteractiveDrawing/bokeh/CDSAlias.py, RootInteractive/InteractiveDrawing/bokeh/CDSAlias.ts, RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts, RootInteractive/InteractiveDrawing/bokeh/CDSJoin.ts, RootInteractive/InteractiveDrawing/bokeh/CDSStack.ts, RootInteractive/InteractiveDrawing/bokeh/ClientLinearFitter.ts, RootInteractive/InteractiveDrawing/bokeh/ColumnFilter.ts, RootInteractive/InteractiveDrawing/bokeh/ConcatenatedString.ts, RootInteractive/InteractiveDrawing/bokeh/CustomJSNAryFunction.ts, RootInteractive/InteractiveDrawing/bokeh/DownsamplerCDS.ts, RootInteractive/InteractiveDrawing/bokeh/HistoNdCDS.ts, RootInteractive/InteractiveDrawing/bokeh/HistoNdProfile.ts, RootInteractive/InteractiveDrawing/bokeh/HistoStatsCDS.ts, RootInteractive/InteractiveDrawing/bokeh/HistogramCDS.ts, RootInteractive/InteractiveDrawing/bokeh/LazyIntersectionFilter.ts, RootInteractive/InteractiveDrawing/bokeh/LazyTabs.py, RootInteractive/InteractiveDrawing/bokeh/LazyTabs.ts, RootInteractive/InteractiveDrawing/bokeh/MultiSelectFilter.ts, RootInteractive/InteractiveDrawing/bokeh/RIFilter.ts, RootInteractive/InteractiveDrawing/bokeh/RangeFilter.ts, RootInteractive/InteractiveDrawing/bokeh/bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/bokehVisJS3DGraph.ts, RootInteractive/InteractiveDrawing/bokeh/test_Alias.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py, RootInteractive/InteractiveDrawing/bokeh/test_surface3d.py, requirements.txt, setup.py
This PR adds support for Bokeh 3.3.1. However, the changes are NOT back compatible, and I'll probably make another pull request with a few bug fixes that can go to a release before this migrations.
Will fix #296
=> Bokeh3 migration

RootInteractive/InteractiveDrawing/bokeh/bokehInteractiveTemplate.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogram.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehDrawSA.py
Partial fix for #350 
This PR also fixes some layout issues with tables
=> Workaround to force bokeh to import mathjax when using bokehInteractiveTemplate getDefaultVars

RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/MLpipeline/MIForestErrPDF.py
This PR fixes a broken legend label for heatmaps
=> Fix legend label for heatmaps

RootInteractive/InteractiveDrawing/bokeh/CDSCompress.py, RootInteractive/InteractiveDrawing/bokeh/CDSCompress.ts, RootInteractive/InteractiveDrawing/bokeh/MultiSelectFilter.ts, RootInteractive/InteractiveDrawing/bokeh/bokehInteractiveTemplate.py, RootInteractive/InteractiveDrawing/bokeh/bokehTools.py, RootInteractive/InteractiveDrawing/bokeh/test_bokehClientHistogramWeight.py, RootInteractive/Tools/compressArray.py
Exactly what the title says.
We checked if it formally worked but forgot that the multiselects were disabled
Further changes added to this pull request described in reply, also fixes most items of #367
=> Fix multiselect filter bug in get as bits + adding dithering option
